NUMBER_OF_BOIDS: 50

LOWER_POS_LIM: [-450.0, 300.0]
UPPER_POS_LIM: [  50.0, 600.0]
LOWER_VEL_LIM: [   0.0, -20.0]
UPPER_VEL_LIM: [  10.0,  20.0]
MOVEMENT_STRENGTH: 0.01
PROXIMITY: 100
FLOCK_SIZE: 10000
FLOCK_WEIGHT: 0.125